// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

package elrond.proto;

public final class TransactionOuterClass {
  private TransactionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Transaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 Nonce = 1;</code>
     * @return The nonce.
     */
    long getNonce();

    /**
     * <code>bytes Value = 2;</code>
     * @return The value.
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <code>bytes RcvAddr = 3;</code>
     * @return The rcvAddr.
     */
    com.google.protobuf.ByteString getRcvAddr();

    /**
     * <code>bytes RcvUserName = 4;</code>
     * @return The rcvUserName.
     */
    com.google.protobuf.ByteString getRcvUserName();

    /**
     * <code>bytes SndAddr = 5;</code>
     * @return The sndAddr.
     */
    com.google.protobuf.ByteString getSndAddr();

    /**
     * <code>bytes SndUserName = 6;</code>
     * @return The sndUserName.
     */
    com.google.protobuf.ByteString getSndUserName();

    /**
     * <code>uint64 GasPrice = 7;</code>
     * @return The gasPrice.
     */
    long getGasPrice();

    /**
     * <code>uint64 GasLimit = 8;</code>
     * @return The gasLimit.
     */
    long getGasLimit();

    /**
     * <code>bytes Data = 9;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>bytes ChainID = 10;</code>
     * @return The chainID.
     */
    com.google.protobuf.ByteString getChainID();

    /**
     * <code>uint32 Version = 11;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>bytes Signature = 12;</code>
     * @return The signature.
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <code>uint32 Options = 13;</code>
     * @return The options.
     */
    int getOptions();
  }
  /**
   * <pre>
   * Transaction holds all the data needed for a value transfer or SC call
   * </pre>
   *
   * Protobuf type {@code Transaction}
   */
  public static final class Transaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Transaction)
      TransactionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Transaction() {
      value_ = com.google.protobuf.ByteString.EMPTY;
      rcvAddr_ = com.google.protobuf.ByteString.EMPTY;
      rcvUserName_ = com.google.protobuf.ByteString.EMPTY;
      sndAddr_ = com.google.protobuf.ByteString.EMPTY;
      sndUserName_ = com.google.protobuf.ByteString.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
      chainID_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Transaction();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              nonce_ = input.readUInt64();
              break;
            }
            case 18: {

              value_ = input.readBytes();
              break;
            }
            case 26: {

              rcvAddr_ = input.readBytes();
              break;
            }
            case 34: {

              rcvUserName_ = input.readBytes();
              break;
            }
            case 42: {

              sndAddr_ = input.readBytes();
              break;
            }
            case 50: {

              sndUserName_ = input.readBytes();
              break;
            }
            case 56: {

              gasPrice_ = input.readUInt64();
              break;
            }
            case 64: {

              gasLimit_ = input.readUInt64();
              break;
            }
            case 74: {

              data_ = input.readBytes();
              break;
            }
            case 82: {

              chainID_ = input.readBytes();
              break;
            }
            case 88: {

              version_ = input.readUInt32();
              break;
            }
            case 98: {

              signature_ = input.readBytes();
              break;
            }
            case 104: {

              options_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TransactionOuterClass.internal_static_Transaction_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TransactionOuterClass.internal_static_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Transaction.class, Builder.class);
    }

    public static final int NONCE_FIELD_NUMBER = 1;
    private long nonce_;
    /**
     * <code>uint64 Nonce = 1;</code>
     * @return The nonce.
     */
    @Override
    public long getNonce() {
      return nonce_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>bytes Value = 2;</code>
     * @return The value.
     */
    @Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int RCVADDR_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString rcvAddr_;
    /**
     * <code>bytes RcvAddr = 3;</code>
     * @return The rcvAddr.
     */
    @Override
    public com.google.protobuf.ByteString getRcvAddr() {
      return rcvAddr_;
    }

    public static final int RCVUSERNAME_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString rcvUserName_;
    /**
     * <code>bytes RcvUserName = 4;</code>
     * @return The rcvUserName.
     */
    @Override
    public com.google.protobuf.ByteString getRcvUserName() {
      return rcvUserName_;
    }

    public static final int SNDADDR_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString sndAddr_;
    /**
     * <code>bytes SndAddr = 5;</code>
     * @return The sndAddr.
     */
    @Override
    public com.google.protobuf.ByteString getSndAddr() {
      return sndAddr_;
    }

    public static final int SNDUSERNAME_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString sndUserName_;
    /**
     * <code>bytes SndUserName = 6;</code>
     * @return The sndUserName.
     */
    @Override
    public com.google.protobuf.ByteString getSndUserName() {
      return sndUserName_;
    }

    public static final int GASPRICE_FIELD_NUMBER = 7;
    private long gasPrice_;
    /**
     * <code>uint64 GasPrice = 7;</code>
     * @return The gasPrice.
     */
    @Override
    public long getGasPrice() {
      return gasPrice_;
    }

    public static final int GASLIMIT_FIELD_NUMBER = 8;
    private long gasLimit_;
    /**
     * <code>uint64 GasLimit = 8;</code>
     * @return The gasLimit.
     */
    @Override
    public long getGasLimit() {
      return gasLimit_;
    }

    public static final int DATA_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes Data = 9;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int CHAINID_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString chainID_;
    /**
     * <code>bytes ChainID = 10;</code>
     * @return The chainID.
     */
    @Override
    public com.google.protobuf.ByteString getChainID() {
      return chainID_;
    }

    public static final int VERSION_FIELD_NUMBER = 11;
    private int version_;
    /**
     * <code>uint32 Version = 11;</code>
     * @return The version.
     */
    @Override
    public int getVersion() {
      return version_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 12;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes Signature = 12;</code>
     * @return The signature.
     */
    @Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    public static final int OPTIONS_FIELD_NUMBER = 13;
    private int options_;
    /**
     * <code>uint32 Options = 13;</code>
     * @return The options.
     */
    @Override
    public int getOptions() {
      return options_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nonce_ != 0L) {
        output.writeUInt64(1, nonce_);
      }
      if (!value_.isEmpty()) {
        output.writeBytes(2, value_);
      }
      if (!rcvAddr_.isEmpty()) {
        output.writeBytes(3, rcvAddr_);
      }
      if (!rcvUserName_.isEmpty()) {
        output.writeBytes(4, rcvUserName_);
      }
      if (!sndAddr_.isEmpty()) {
        output.writeBytes(5, sndAddr_);
      }
      if (!sndUserName_.isEmpty()) {
        output.writeBytes(6, sndUserName_);
      }
      if (gasPrice_ != 0L) {
        output.writeUInt64(7, gasPrice_);
      }
      if (gasLimit_ != 0L) {
        output.writeUInt64(8, gasLimit_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(9, data_);
      }
      if (!chainID_.isEmpty()) {
        output.writeBytes(10, chainID_);
      }
      if (version_ != 0) {
        output.writeUInt32(11, version_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(12, signature_);
      }
      if (options_ != 0) {
        output.writeUInt32(13, options_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nonce_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, nonce_);
      }
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      if (!rcvAddr_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, rcvAddr_);
      }
      if (!rcvUserName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, rcvUserName_);
      }
      if (!sndAddr_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, sndAddr_);
      }
      if (!sndUserName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, sndUserName_);
      }
      if (gasPrice_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, gasPrice_);
      }
      if (gasLimit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, gasLimit_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, data_);
      }
      if (!chainID_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, chainID_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, version_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, signature_);
      }
      if (options_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, options_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Transaction)) {
        return super.equals(obj);
      }
      Transaction other = (Transaction) obj;

      if (getNonce()
          != other.getNonce()) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!getRcvAddr()
          .equals(other.getRcvAddr())) return false;
      if (!getRcvUserName()
          .equals(other.getRcvUserName())) return false;
      if (!getSndAddr()
          .equals(other.getSndAddr())) return false;
      if (!getSndUserName()
          .equals(other.getSndUserName())) return false;
      if (getGasPrice()
          != other.getGasPrice()) return false;
      if (getGasLimit()
          != other.getGasLimit()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getChainID()
          .equals(other.getChainID())) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (!getSignature()
          .equals(other.getSignature())) return false;
      if (getOptions()
          != other.getOptions()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNonce());
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + RCVADDR_FIELD_NUMBER;
      hash = (53 * hash) + getRcvAddr().hashCode();
      hash = (37 * hash) + RCVUSERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getRcvUserName().hashCode();
      hash = (37 * hash) + SNDADDR_FIELD_NUMBER;
      hash = (53 * hash) + getSndAddr().hashCode();
      hash = (37 * hash) + SNDUSERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSndUserName().hashCode();
      hash = (37 * hash) + GASPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGasPrice());
      hash = (37 * hash) + GASLIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGasLimit());
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + CHAINID_FIELD_NUMBER;
      hash = (53 * hash) + getChainID().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptions();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Transaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Transaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Transaction holds all the data needed for a value transfer or SC call
     * </pre>
     *
     * Protobuf type {@code Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Transaction)
        TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransactionOuterClass.internal_static_Transaction_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransactionOuterClass.internal_static_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Transaction.class, Builder.class);
      }

      // Construct using elrond.proto.TransactionOuterClass.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        nonce_ = 0L;

        value_ = com.google.protobuf.ByteString.EMPTY;

        rcvAddr_ = com.google.protobuf.ByteString.EMPTY;

        rcvUserName_ = com.google.protobuf.ByteString.EMPTY;

        sndAddr_ = com.google.protobuf.ByteString.EMPTY;

        sndUserName_ = com.google.protobuf.ByteString.EMPTY;

        gasPrice_ = 0L;

        gasLimit_ = 0L;

        data_ = com.google.protobuf.ByteString.EMPTY;

        chainID_ = com.google.protobuf.ByteString.EMPTY;

        version_ = 0;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        options_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TransactionOuterClass.internal_static_Transaction_descriptor;
      }

      @Override
      public Transaction getDefaultInstanceForType() {
        return Transaction.getDefaultInstance();
      }

      @Override
      public Transaction build() {
        Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Transaction buildPartial() {
        Transaction result = new Transaction(this);
        result.nonce_ = nonce_;
        result.value_ = value_;
        result.rcvAddr_ = rcvAddr_;
        result.rcvUserName_ = rcvUserName_;
        result.sndAddr_ = sndAddr_;
        result.sndUserName_ = sndUserName_;
        result.gasPrice_ = gasPrice_;
        result.gasLimit_ = gasLimit_;
        result.data_ = data_;
        result.chainID_ = chainID_;
        result.version_ = version_;
        result.signature_ = signature_;
        result.options_ = options_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Transaction) {
          return mergeFrom((Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Transaction other) {
        if (other == Transaction.getDefaultInstance()) return this;
        if (other.getNonce() != 0L) {
          setNonce(other.getNonce());
        }
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        if (other.getRcvAddr() != com.google.protobuf.ByteString.EMPTY) {
          setRcvAddr(other.getRcvAddr());
        }
        if (other.getRcvUserName() != com.google.protobuf.ByteString.EMPTY) {
          setRcvUserName(other.getRcvUserName());
        }
        if (other.getSndAddr() != com.google.protobuf.ByteString.EMPTY) {
          setSndAddr(other.getSndAddr());
        }
        if (other.getSndUserName() != com.google.protobuf.ByteString.EMPTY) {
          setSndUserName(other.getSndUserName());
        }
        if (other.getGasPrice() != 0L) {
          setGasPrice(other.getGasPrice());
        }
        if (other.getGasLimit() != 0L) {
          setGasLimit(other.getGasLimit());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getChainID() != com.google.protobuf.ByteString.EMPTY) {
          setChainID(other.getChainID());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        if (other.getOptions() != 0) {
          setOptions(other.getOptions());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Transaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long nonce_ ;
      /**
       * <code>uint64 Nonce = 1;</code>
       * @return The nonce.
       */
      @Override
      public long getNonce() {
        return nonce_;
      }
      /**
       * <code>uint64 Nonce = 1;</code>
       * @param value The nonce to set.
       * @return This builder for chaining.
       */
      public Builder setNonce(long value) {
        
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 Nonce = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNonce() {
        
        nonce_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes Value = 2;</code>
       * @return The value.
       */
      @Override
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>bytes Value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes Value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString rcvAddr_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes RcvAddr = 3;</code>
       * @return The rcvAddr.
       */
      @Override
      public com.google.protobuf.ByteString getRcvAddr() {
        return rcvAddr_;
      }
      /**
       * <code>bytes RcvAddr = 3;</code>
       * @param value The rcvAddr to set.
       * @return This builder for chaining.
       */
      public Builder setRcvAddr(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rcvAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes RcvAddr = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRcvAddr() {
        
        rcvAddr_ = getDefaultInstance().getRcvAddr();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString rcvUserName_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes RcvUserName = 4;</code>
       * @return The rcvUserName.
       */
      @Override
      public com.google.protobuf.ByteString getRcvUserName() {
        return rcvUserName_;
      }
      /**
       * <code>bytes RcvUserName = 4;</code>
       * @param value The rcvUserName to set.
       * @return This builder for chaining.
       */
      public Builder setRcvUserName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rcvUserName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes RcvUserName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRcvUserName() {
        
        rcvUserName_ = getDefaultInstance().getRcvUserName();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString sndAddr_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes SndAddr = 5;</code>
       * @return The sndAddr.
       */
      @Override
      public com.google.protobuf.ByteString getSndAddr() {
        return sndAddr_;
      }
      /**
       * <code>bytes SndAddr = 5;</code>
       * @param value The sndAddr to set.
       * @return This builder for chaining.
       */
      public Builder setSndAddr(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sndAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes SndAddr = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSndAddr() {
        
        sndAddr_ = getDefaultInstance().getSndAddr();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString sndUserName_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes SndUserName = 6;</code>
       * @return The sndUserName.
       */
      @Override
      public com.google.protobuf.ByteString getSndUserName() {
        return sndUserName_;
      }
      /**
       * <code>bytes SndUserName = 6;</code>
       * @param value The sndUserName to set.
       * @return This builder for chaining.
       */
      public Builder setSndUserName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sndUserName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes SndUserName = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSndUserName() {
        
        sndUserName_ = getDefaultInstance().getSndUserName();
        onChanged();
        return this;
      }

      private long gasPrice_ ;
      /**
       * <code>uint64 GasPrice = 7;</code>
       * @return The gasPrice.
       */
      @Override
      public long getGasPrice() {
        return gasPrice_;
      }
      /**
       * <code>uint64 GasPrice = 7;</code>
       * @param value The gasPrice to set.
       * @return This builder for chaining.
       */
      public Builder setGasPrice(long value) {
        
        gasPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 GasPrice = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearGasPrice() {
        
        gasPrice_ = 0L;
        onChanged();
        return this;
      }

      private long gasLimit_ ;
      /**
       * <code>uint64 GasLimit = 8;</code>
       * @return The gasLimit.
       */
      @Override
      public long getGasLimit() {
        return gasLimit_;
      }
      /**
       * <code>uint64 GasLimit = 8;</code>
       * @param value The gasLimit to set.
       * @return This builder for chaining.
       */
      public Builder setGasLimit(long value) {
        
        gasLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 GasLimit = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearGasLimit() {
        
        gasLimit_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes Data = 9;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes Data = 9;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes Data = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString chainID_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes ChainID = 10;</code>
       * @return The chainID.
       */
      @Override
      public com.google.protobuf.ByteString getChainID() {
        return chainID_;
      }
      /**
       * <code>bytes ChainID = 10;</code>
       * @param value The chainID to set.
       * @return This builder for chaining.
       */
      public Builder setChainID(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chainID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes ChainID = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearChainID() {
        
        chainID_ = getDefaultInstance().getChainID();
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>uint32 Version = 11;</code>
       * @return The version.
       */
      @Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>uint32 Version = 11;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 Version = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes Signature = 12;</code>
       * @return The signature.
       */
      @Override
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes Signature = 12;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes Signature = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      private int options_ ;
      /**
       * <code>uint32 Options = 13;</code>
       * @return The options.
       */
      @Override
      public int getOptions() {
        return options_;
      }
      /**
       * <code>uint32 Options = 13;</code>
       * @param value The options to set.
       * @return This builder for chaining.
       */
      public Builder setOptions(int value) {
        
        options_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 Options = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearOptions() {
        
        options_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Transaction)
    }

    // @@protoc_insertion_point(class_scope:Transaction)
    private static final Transaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Transaction();
    }

    public static Transaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Transaction>
        PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
      @Override
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Transaction> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    @Override
    public Transaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Transaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Transaction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021transaction.proto\"\357\001\n\013Transaction\022\r\n\005N" +
      "once\030\001 \001(\004\022\r\n\005Value\030\002 \001(\014\022\017\n\007RcvAddr\030\003 \001" +
      "(\014\022\023\n\013RcvUserName\030\004 \001(\014\022\017\n\007SndAddr\030\005 \001(\014" +
      "\022\023\n\013SndUserName\030\006 \001(\014\022\020\n\010GasPrice\030\007 \001(\004\022" +
      "\020\n\010GasLimit\030\010 \001(\004\022\014\n\004Data\030\t \001(\014\022\017\n\007Chain" +
      "ID\030\n \001(\014\022\017\n\007Version\030\013 \001(\r\022\021\n\tSignature\030\014" +
      " \001(\014\022\017\n\007Options\030\r \001(\rB\022\n\020com.elrond.prot" +
      "ob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Transaction_descriptor,
        new String[] { "Nonce", "Value", "RcvAddr", "RcvUserName", "SndAddr", "SndUserName", "GasPrice", "GasLimit", "Data", "ChainID", "Version", "Signature", "Options", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
